version: '3.6'

services:

  node:
    container_name: node
    build:
      context: ./services/node
      dockerfile: Dockerfile-dev
    volumes:
      - './services/node:/usr/src/app'
      - '/usr/src/app/node_modules'
#    ports:
#      - 3001:3001
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mysql


  mysql:
    container_name: mysql
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: banana
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: my_db
    volumes:
      - './services/db/schema:/docker-entrypoint-initdb.d'

  client:
    container_name: client
    labels:
      traefik.frontend.passHostHeader: 'true'
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
#    ports:
#      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - node

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - node
      - client


