version: '3.6'

services:

  node-prod:
    container_name: node
    build:
      context: ./services/node
      dockerfile: Dockerfile-prod
    volumes:
      - './services/node:/usr/src/app'
      - '/usr/src/app/node_modules'
#    ports:
#      - 3001:3001
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: banana
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: my_db
    volumes:
      - './services/db/schema:/docker-entrypoint-initdb.d'

  client-prod:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
#    volumes:
#      - './services/client/:/usr/src/app'
#      - '/usr/src/app/node_modules'
#    expose:
#      - 80
    environment:
      - NODE_ENV=production
#      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - node-prod

  nginx-prod:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - node-prod
      - client-prod
